pickle_dir1 : /scratch/usr/hhpmbate/chroma_3pt/32x64/b5p50kp121040kp120620/six_point_fn_theta3/kappa1/pickle/
pickle_dir2 : /scratch/usr/hhpmbate/chroma_3pt/32x64/b5p50kp121040kp120620/six_point_fn_theta3/kappa2/pickle/
analysis_dir : /scratch/usr/hhpmbate/chroma_3pt/32x64/b5p50kp121040kp120620/six_point_fn_theta3/analysis/
onlytwist2 : True
time_choice : 4
delta_t : 2
t_range0 : 11
t_range1 : 24
lmb_i : 0
lmb_f : 0.05
lmb_init : 4
lmb_final : 8
plotting : True
tmin_nucl : 12
tmin_sigma : 12
tmax_nucl : 24
tmax_sigma : 24
tmax_ratio : 24
