pickle_dir1 : /scratch/usr/hhpmbate/chroma_3pt/32x64/b5p50kp121040kp120620/six_point_fn_onlytwist/kappa1/pickle/
pickle_dir2 : /scratch/usr/hhpmbate/chroma_3pt/32x64/b5p50kp121040kp120620/six_point_fn_onlytwist/kappa2/pickle/
analysis_dir : /scratch/usr/hhpmbate/chroma_3pt/32x64/b5p50kp121040kp120620/six_point_fn_onlytwist/analysis/
time_choice : 2
delta_t : 2
t_range0 : 4
t_range1 : 9
lmb_val : 0.04