lattice: Feyn-Hell_kp21374891798173
kappa: 9
geom: 32x32
lmb_i : 0
lmb_f : 0.08
tmin_nucl : 12
tmin_sigma : 12
tmax_nucl : 24
tmax_sigma : 24
tmax_ratio : 24
lmb_val : 0.025
plotting : False
time_loop : False