lattice: 'Feyn-Hell_kp121040kp120620/'
kappa: 'kp121040kp120620/'
# geom: '48x96'
beta: 'b5p50'
csw: 'c2p6500'
L: 32
T: 64
a: 0.068
baryons:
  - name: proton
    label: p
    charge: [2/3, -1/3]
  - name: neutron
    label: n
    charge: [-1/3, 2/3]

baryon_types:
  - 'barspec_nucleon_rel'       # Unpolarized projector
  - 'barspec_nucleon_rel_timerev'
  - 'barspec_noise_proton'      # Polarized(z)+ projector
  - 'barspec_noise_proton_timerev'
  - 'barspec_nucleon2'          # Polarized(z)- projector
  - 'barspec_nucleon2_timerev'

ferm_act_str : ['unpreconditioned_slrc', 'unprec_slrc_feynhell']
kappacombs : ['kp122130kp122130', 'kp122130kp121756', 'kp121756kp122130']
# kappacombs : ['kp121756kp122130','kp122130kp121756']
lambdas : [0.0001, 0.001]
lambda_str : ['lp0001+p0000i_lp0001+p0000i', 'lp001+p000i_lp001+p000i']
quarks: ['u','d','s']
src_smearing : ['sh_gij_p21_30']
snk_smearing : ['sh_gij_p21_30', 'pt']
qval: [[0,0,0], [2,2,0], [4,2,2], [4,4,2], [6,0,0], [6,4,2]]

operators :
  gammas:
    - 2
    - 8
  momenta:
    -
      - [[2,2,0],[-2,-2,0]]
      - [[4,2,2],[-4,-2,-2]]
      - [[4,4,2],[-4,-4,-2]]
      - [[6,0,0],[-6,0,0]]
      - [[6,4,2],[-6,-4,-2]]
    -
      - [[0,0,0],[0,0,0]]
      - [[2,2,0],[-2,-2,0]]
      - [[4,2,2],[-4,-2,-2]]
      - [[4,4,2],[-4,-4,-2]]
      - [[6,0,0],[-6,0,0]]
      - [[6,4,2],[-6,-4,-2]]

nboot : 500
nbin : 1
    
xlim: 32
norma: [1e16,1e16,1e16]

bounds2pt: [[-inf,inf],[-1.,1.],[-inf,inf],[-1.,3.]]
boundsratio: [[-inf,inf],[-1e-1,1e-1],[-inf,inf],[-1e-1,1e-1]]

fit_twopt: True
fit_ratio: True
fit_oneexp: True
fit_twoexp: False

# time_limits: [[3, 18], [12, 29]]
# time_limits_ratio1: [[3, 18], [12, 29]]
# time_limits_ratio2: [[3, 18], [12, 29]]
# time_limits: [[7, 8], [12, 13]]
# time_limits_ratio1: [[7, 8], [12, 13]]
# time_limits_ratio2: [[7, 8], [12, 13]]
# time_limits: [[7, 7], [39, 40]]
# time_limits_ratio1: [[1, 16], [10, 33]]
# time_limits_ratio2: [[1, 16], [10, 25]]

time_limits: [[7, 23], [13, 40]]
time_limits_energy:
  - [[3, 22], [29,33]]
  - [[3, 18], [25, 28]]
  - [[3, 16], [18, 22]]
  - [[3, 15], [15, 18]]
  - [[3, 15], [15, 21]]
  - [[2, 13], [11, 15]]


time_limits_ratio1:
  - [[3, 11], [15, 28]]
  - [[3, 11], [13, 22]]
  - [[2, 9], [11, 21]]
  - [[2, 9], [7, 17]]
  - [[2, 9], [6, 15]]
time_limits_ratio2:
  # - [[7, 12], [21, 24]]
  # - [[4, 10], [18, 20]]
  - [[3, 11], [21,30]]
  - [[3, 11], [15, 30]]
  - [[3, 11], [13, 25]]
  - [[3, 11], [6, 23]]
  - [[3, 11], [6, 18]]
  - [[2, 9], [6, 15]]


time_limits_ratio1_2:
  - [[1, 6], [18, 20]]
  - [[1, 6], [13, 16]]
  - [[1, 9], [11, 14]]
  - [[1, 9], [9, 13]]
  - [[1, 9], [8, 12]]
time_limits_ratio2_2:
  - [[1, 6], [21, 24]]
  - [[1, 6], [18, 20]]
  - [[1, 9], [13, 16]]
  - [[1, 11], [8, 16]]
  - [[1, 11], [8, 16]]
  - [[1, 9], [8, 12]]


ylim_ratios:
  -
    - [[-0.00004, 0.00001], [-0.00001, 0.000015]]
    - [[-0.00004, 0.00001], [-0.00001, 0.000015]]
    - [[-0.00004, 0.00001], [-0.00001, 0.000015]]
    - [[-0.00004, 0.00001], [-0.00001, 0.000015]]
    - [[-0.00004, 0.00001], [-0.00001, 0.000015]]
  -
    - [[0.0002, 0.00025], [0.00008, 0.00014]]
    - [[-0.00001, 0.00005], [-0.00001, 0.00003]]
    - [[-0.00001, 0.00005], [-0.00001, 0.00003]]
    - [[-0.00001, 0.00005], [-0.00001, 0.00003]]
    - [[-0.00001, 0.00005], [-0.00001, 0.00003]]
    - [[-0.00001, 0.00005], [-0.00001, 0.00003]]
