pickle_dir1 : /scratch/usr/hhpmbate/chroma_3pt/32x64/b5p50kp121040kp120620/six_point_fn_theta4/kappa1/pickle/
pickle_dir2 : /scratch/usr/hhpmbate/chroma_3pt/32x64/b5p50kp121040kp120620/six_point_fn_theta4/kappa2/pickle/
analysis_dir : /scratch/usr/hhpmbate/chroma_3pt/32x64/b5p50kp121040kp120620/six_point_fn_theta4/analysis/
name : theta4
onlytwist2 : True
time_choice : 6
delta_t : 4
t_range0 : 11
t_range1 : 24
lmb_init : 1
lmb_final : 10
tmin_nucl : 12
tmax_nucl : 24
tmin_ratio : 10
tmax_ratio : 20
plotting: True