pickle_dir1 : /scratch/usr/hhpmbate/chroma_3pt/32x64/b5p50kp121040kp120620/six_point_fn_theta7/kappa1/pickle/
pickle_dir2 : /scratch/usr/hhpmbate/chroma_3pt/32x64/b5p50kp121040kp120620/six_point_fn_theta7/kappa2/pickle/
analysis_dir : /scratch/usr/hhpmbate/chroma_3pt/32x64/b5p50kp121040kp120620/six_point_fn_theta7/analysis/
name : theta7
onlytwist2 : True
time_choice : 6
delta_t : 4
t_range0 : 7
t_range1 : 19
lmb_init : 2
lmb_final : 12
tmin_nucl : 10
tmax_nucl : 21
tmin_ratio : 8
tmax_ratio : 17
lmb_i : 0
lmb_f : 0.05
lmb_num : 15
plotting: True
runname: 'run \#5'
runnumber: 5