pickle_dir1 : /scratch/usr/hhpmbate/chroma_3pt/32x64/b5p50kp121040kp120620/six_point_fn_theta5/kappa1/pickle/
pickle_dir2 : /scratch/usr/hhpmbate/chroma_3pt/32x64/b5p50kp121040kp120620/six_point_fn_theta5/kappa2/pickle/
analysis_dir : /scratch/usr/hhpmbate/chroma_3pt/32x64/b5p50kp121040kp120620/six_point_fn_theta5/analysis/
name : theta5
onlytwist2 : True
time_choice : 4
delta_t : 2
t_range0 : 11
t_range1 : 24
lmb_init : 1
lmb_final : 13
tmin_nucl : 12
tmax_nucl : 24
tmin_ratio : 8
tmax_ratio : 20
lmb_i : 0
lmb_f : 0.05
lmb_num : 15